version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - '6378:6379'
  postgres-db:
    image: postgres:16
    container_name:
      postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=CourseWorkDRF
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  django-app:
    build:
      dockerfile: Dockerfile
      context: .
    command: sh -c "sleep 3 && python3 manage.py migrate && python3 manage.py runserver 127.0.0.1:8000"
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      postgres-db:
        condition: service_healthy
  celery:
      build: .
      tty: true
      env_file:
        - .env
      command: sh -c "sleep 5 && celery -A config worker -l INFO"
      depends_on:
          - redis
          - django-app

  celery_beat:
    build: .
    tty: true
    env_file:
      - .env
    command: sh -c "sleep 10 && celery -A config beat -l info -S django"
    depends_on:
      - celery
      - redis
      - django-app
volumes:
  pg_data: