# Generated by Django 4.2.7 on 2023-11-06 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='где угодно', max_length=100, verbose_name='место выполнения')),
                ('time', models.TimeField(verbose_name='время выполнения')),
                ('action', models.CharField(max_length=500, verbose_name='действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('period', models.CharField(choices=[('1', 'один день в неделю'), ('2', 'два дня в неделю'), ('3', 'три дня в неделю'), ('4', 'четыре дня в неделю'), ('5', 'пять дней в неделю'), ('6', 'шесть дней в неделю'), ('daily', 'ежедневно')], default='daily', max_length=20, verbose_name='периодичность привычки')),
                ('reward', models.CharField(max_length=500, verbose_name='награда за выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='публикация')),
                ('linked', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habits', verbose_name='связанная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
