# Generated by Django 4.2.7 on 2023-11-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habits_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='reward',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='награда за выполнение'),
        ),
    ]
