# Generated by Django 4.2.7 on 2023-11-06 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habits_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='habits',
            name='limit',
            field=models.IntegerField(default=60, verbose_name='время на выполнение'),
        ),
    ]
