# Generated by Django 4.2.7 on 2023-11-08 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='last_attempt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='последняя отправка'),
        ),
    ]
